### ISSUE TITLE
EDMarketConnecter suddenly doesn't work after update

### ISSUE THREAD

**Issue by Julexar** [EDCD/EDMarketConnector#1126]
**Please complete the following information:**
 - Version: 5.0.4+2ba8cf1
 - Game Version: Elite Dangerous: Horizons
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Browser chrome
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file). 
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6564425/EDMarketConnector.log)

     1. %TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File]
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6564424/EDMarketConnector-debug.log)

**Describe the bug**
I always get missing credentials and I accidentally removed the authorisation from frontier and now I can't authorise it again (I tried uninstalling and reinstalling but it didn't work)

**To Reproduce**
1. Have an older version
2. Update it
3. Start Elite Dangerous
4. suddenly doesn't work anymore

**Expected behavior**
I didn't expect there to be any issues but after I updated the program it suddenly didn't work anymore

**Comment by Athanasius** [comment]
Just to be sure... your latest activity with the game client; did it include logging all the way into the game, or only to the main menu ?

**Comment by Athanasius** [comment]
> Just to be sure... your latest activity with the game client; did it include logging all the way into the game, or only to the main menu ?

I ask because I can re-create your latest logfile contents with:

1. Start the game client and wait for it to bring up the Main Menu
2. Do NOT do anything else with the game client.
3. (Re-)start EDMarketConnector.exe, version 5.0.4
4. Attempt to use "File" > "Save Raw Data".

This fails due to things outlined in:

https://github.com/EDCD/EDMarketConnector/wiki/New-user-guide#you-need-to-be-fully-logged-into-the-game-ie-opensolo-play
https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out

**Comment by Julexar** [comment]
Still doesn't work, here are the files again:

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6564987/EDMarketConnector.log)

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6564988/EDMarketConnector-debug.log)

**Comment by Athanasius** [comment]
Please describe exactly all the steps you take, with both the game and the EDMarketConnector.exe application from the start through to when "it doesn't work".

The log files show:

1. start up of EDMarketConnector.exe
2. It finds a Journal file, parses it to the end, and then enters its normal processing.
3. An attempt to use "File" > "Save Raw Data", which doesn't work because of missing credentials.  The only immediate situation I can think of for that to be the case, without *other* logging also happening, is not actually being in-game.

```python
2021-05-29 18:25:13.438 - DEBUG - 17848:18376:18376 monitor.EDLogs.worker:321: Starting on logfile "C:/Users/Agando/Saved Games/Frontier Developments/Elite Dangerous\Journal.210529182445.01.log"
2021-05-29 18:25:13.439 - DEBUG - 17848:6652:6652 monitor.EDLogs.start:240: Done
2021-05-29 18:25:13.443 - DEBUG - 17848:6652:6652 monitor.EDLogs.start:242: Done.
2021-05-29 18:25:13.449 - DEBUG - 17848:18376:18376 monitor.EDLogs.worker:344: Now at end of latest file.
2021-05-29 18:25:13.517 - DEBUG - 17848:18376:18376 monitor.EDLogs.worker:381: Entering loop...
2021-05-29 18:25:16.858 - ERROR - 17848:6652:6652 companion.Session.login:464: self.credentials is None
2021-05-29 18:25:16.859 - DEBUG - 17848:6652:6652 EDMarketConnector.AppWindow.save_raw:1415: "other" exception
Traceback (most recent call last):
  File "EDMarketConnector.py", line 1383, in save_raw
  File "companion.pyc", line 618, in station
  File "companion.pyc", line 531, in query
  File "companion.pyc", line 465, in login
companion.CredentialsError: Missing credentials
```

It might be worth opening regedit.exe, then:

1. Navigate to `Computer\HKEY_CURRENT_USER\SOFTWARE\Marginal\EDMarketConnector`
2. Check what the `cmdrs` key has in it.  And if it does actually have your Commander name in it properly, then:
3. Check if there's anything in `fdev_apikeys`.
4. If there is and it's not working then, quit out of EDMarketConnector.exe then delete **both** of those keys and re-start it.
5. You will absolutely then need to get fully in-game for your Commander name to be picked up and a fresh Frontier Authorisation triggered (either by having the Auto update option on 'Output' enabled, or pressing the 'Update' button **once in-game**).

**Comment by Julexar** [comment]
Thank you, now it works again!
