### ISSUE TITLE
"Update" always says Frontier lagging just after boarding in a settlement.

### ISSUE THREAD

**Issue by leonardofelin** [EDCD/EDMarketConnector#1166]
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6642283/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6642284/EDMarketConnector-debug.log)

**Describe the bug**
When I press the Update button just after boarding the ship in a settlement, status line says "Error: Frontier server is lagging".

Aprox. timestamp in the logs: 10:49.xx

**Comment by A-UNDERSCORE-D** [comment]
Appears your CAPI login is broken. Did you skip login when it popped up in a browser?

**Comment by Athanasius** [comment]
There's something weird in that log file (plain, not debug).  It has properly formatted log lines *and* then duplicates of those without the timestamp prefix, and in general without the correct format.  It's like there's an extra logging channel set up ?

I can only assume it's something to do with one of the plugins: EDMC-Screenshot, EDSM-RSE or SpanshRouter.

**Comment by Athanasius** [comment]
And to me all of that auth flow looks OK.

The 'error' is likely more to do with the logic that checks CAPI location data against latest Journal location data.  It's gotten even twistier with all the Odyssey on-foot/taxi/embark etc situations.

**Comment by leonardofelin** [comment]
Yeah, I changed the log to DEBUG before trying again. I'll to some more focused tests and a clean log later today. Trying to get an engineer unlocked now.

**Comment by leonardofelin** [comment]
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6644064/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6644065/EDMarketConnector-debug.log)

Clean logs.
Steps to reproduce the error:
1. Land on Odyssey settlement (Arai's Mine | IAH BULU)
2. Loot the place
3. Board ship
4. Hit "Update"
5. Error is displayed

**Comment by leonardofelin** [comment]
Raw data saved just after the error:
[Iah Bulu.Arai's Mine.2021-06-13T11.34.30.txt](https://github.com/EDCD/EDMarketConnector/files/6644087/Iah.Bulu.Arai.s.Mine.2021-06-13T11.34.30.txt)

**Comment by Athanasius** [comment]
A 'fix' for this is in `develop` now.  All it actually does is change the status line error message to be specific to this, rather than a misleading/false "server lagging" one.

With the current Journal events we can't reliably verify that the CAPI location (system and starport) matches where we think we are in this situation.

As noted on discord, all the 'Update' button *does* is request new CAPI data for market, shipyard and outfitting for the station you're at (if you are), and send it over EDDN.  It's not necessary for things like sending updated shiplocker materials to Inara.  That will happen automatically from Journal events alone.
