### ISSUE TITLE
EDMC logging on trace level without --trace option

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1239]
- Version: 5.1.3+1a0b4ae
 - Game Version: Live
 - OS: Windows 10
 - OS Locale: Russian

[5.1.3_00.log](https://github.com/EDCD/EDMarketConnector/files/6971782/5.1.3_00.log)
[EDMarketConnector-debug-5.1.3_00.log](https://github.com/EDCD/EDMarketConnector/files/6971783/EDMarketConnector-debug-5.1.3_00.log)

**Describe the bug**
EDMC putting log entries on TRACE level but isn't ran with `--trace` option

**To Reproduce**
1. Run EDMC, I use 5.1.3 release from msi installer
2. Check out debug logs
3. See TRACE level log entries

**Expected behavior**
No TRACE level log entries without --trace CL option

**Screenshots**
None

**Additional context**
I cutted inara events from debug log since it contains my inara api key

**Comment by A-UNDERSCORE-D** [comment]
Intentional. see:

 [# Yes, we always want these rotated files to be at TRACE level](https://github.com/EDCD/EDMarketConnector/blob/e7f8fea250b95e35d274c1a6f36b9dee4bab721d/EDMCLogging.py#L160-L160)

The loglevel is for the console log, rather than for the output. Users on windows running from our binaries wont see the console, but if they could it wouldnt be flooded with trace logs. This is why we have two (sometimes three!) files

**Comment by norohind** [comment]
Then any chance some big trace messages will be under `trace_on`? Inara plugin - one thing worries me.
