### ISSUE TITLE
EngineerProgress has neither Engineers nor Progress

### ISSUE THREAD

**Issue by foresto** [EDCD/EDMarketConnector#1275]
**Please complete the following information:**
 - Version: 5.1.3
 - Game Version: Horizons (Odyssey compatibility update 3.8.04)
 - Relevant log excerpt:
    monitor.EDLogs.start:246: Done.
    monitor.EDLogs.event_valid_engineerprogress:1754: EngineerProgress has neither 'Engineers' nor 'Progress': entry=OrderedDict([('timestamp', '2021-09-20T05:22:35Z'), ('event', 'EngineerProgress'), ('Engineer', 'Elvira Martuuk'), ('EngineerID', 300160), ('Rank', 5)])
    monitor.EDLogs.worker:351: Now at end of latest file.

**Describe the bug**
The above warning is being logged whenever I start EDMarketConnector.

Based on the data structure in the above warning message and a glance at the code, it looks to me like the ED log data contains a structure that EDMarketConnector doesn't know how to handle: An `EngineerProgress` message that contains neither a list nor a `Progress` key.

Perhaps this is a result of Frontier making a small change to their log format?

**To Reproduce**
1. Play the game.
2. Exit the game.
3. Start EDMarketConnector
4. See the warning in the log

**Expected behavior**
I expect this ED log data structure to be handled, not trigger a warning.

**Additional context**
This warning appeared shortly after unlocking grade 5 frame shift drive engineering at Elvira's workshop.

**Comment by alterNERDtive** [comment]
> **Expected behavior**
> I expect this ED log data structure to be handled, not trigger a warning.

Have you looked at the underlying event in the journal? I have the sneaking suspicion it _is_ being handled, by printing that line to the log :)

**Comment by Athanasius** [comment]
This is working as designed.  The issue is that the game should write one of two forms of the `EngineerProgress` event.  The first is when you login to the game and it cites your current progress, which is the 'Engineers' form in the message.  The second is when you progress with an Engineer during a game session, that's the 'Progress' form in the message.

If it has neither that's a game bug, tell Frontier, quoting the relevant line from your journal file.
