### ISSUE TITLE
Unable to start.

### ISSUE THREAD

**Issue by denisgre** [EDCD/EDMarketConnector#1353]
Just installed latest version but it is not trying to login to my Frontier account. Nothing in settings is acessable and all edmc fields shown are blank. Pressing Status key shows "Don't yet know your commander name".

Denis.

**Comment by alterNERDtive** [comment]
Have you started the game and fully logged in?

**Comment by denisgre** [comment]
Uninstalled and re-installed. No change.

**Comment by denisgre** [comment]
I normally start edmc first then start game. Always done it this way for last few years.

**Comment by Athanasius** [comment]
> I normally start edmc first then start game. Always done it this way for last few years.

If the latest Journal file didn't contain at least one login fully into the game then EDMC can't know who you are.  Try it and report back.

**Comment by Athanasius** [comment]
Ref: https://github.com/EDCD/EDMarketConnector/wiki/New-user-guide#you-need-to-be-fully-logged-into-the-game-ie-opensolo-play

**Comment by denisgre** [comment]
OK, that worked but NEVER had to do that previously and I have used edmc for a long time. Many thanks Athanasius.

**Comment by Athanasius** [comment]
As I said above, the issue would be that the last time you started the game client, that's *all* you did, no login to the full game.  That left the latest Journal file without the information of your commander name, which is necessary to know which settings to use (due to multi-account support).

We could possibly make this a little more obvious, it's on the list.
