### ISSUE TITLE
EDMC main window does not start minimized if launched with START /MIN

### ISSUE THREAD

**Issue by parduz** [EDCD/EDMarketConnector#1379]
I have a BATCH file to launch all the app i use aside of Elite Dangerous with just one click.
The relevant line is
`START /MIN "" "!ExeFileName!"`
and should launch the programs minimized.

EDMC is (so far) the only program that does not start minimized but shows his main form.

**Comment by AJH16** [comment]
I see the same behavior.  This looks like it might be helpful: https://stackoverflow.com/questions/2319838/open-a-program-with-python-minimized-or-hidden

**Comment by Loapu** [comment]
I have the same problem. Neither `start /min "" "<EDMC>"` inside CMD nor `Start-Process "<EDMC>" -WindowStyle Minimized` in PowerShell seem to work.

**Comment by Rixxan** [comment]
So because of how EDMC is built off of Tkinter'd python, our options are sort of limited. Realistically, EDMC's EXE launches a console window which then launches the *actual* window, and it doesn't pass inheritance. So the program is respecting your wishes, it's just tkinter being tkinter and its children being rebellious and not following instructions.

I have found a way to imitate the functionality you're looking for. In a future release, if this code is included it would be achieved by running `EDMarketConnector.exe --start_min`. 

Would that be of interest to either of you? @Loapu @parduz

**Comment by Loapu** [comment]
Hi, in my opinion this workaround seems sufficient enough.

**Comment by parduz** [comment]
I agree, the workaround seems sufficient enough.

> So the program is respecting your wishes
Given that the "console launcher" is able to get the `/min` parameter, I wonder if it could then handle the workaround by himself, adding the new "`--start_min`" parameter to the final window.

**Comment by Rixxan** [comment]
> I agree, the workaround seems sufficient enough.
> 
> > So the program is respecting your wishes
> 
> Given that the "console launcher" is able to get the `/min` parameter, I wonder if it could then handle the workaround by himself, adding the new "`--start_min`" parameter to the final window.

Ideally? ... maybe? But I'm not sure about that nor do I really know how do do that.
