### ISSUE TITLE
Add link to EDMarketConnector.exe to desktop

### ISSUE THREAD

**Issue by VAKazakov** [EDCD/EDMarketConnector#1394]
**Describe the enhancement**

A clear and concise description of what you would like changed or added
Can you add link to exe upon install?

**Expected behavior**

A clear and concise description of what you expect to happen.
In Desktop folder of user/users (dunno if there is much sence to place link only to actual user) should appear link to exe of EDMC.

**Considered workarounds**

Workarounds you may have considered can help us with how to implement your idea.
Open install dir, right button click on exe, send > desktop (create link)

**Additional context**

Add any other context about your request here

**Comment by Athanasius** [comment]
This will have to be dependent on https://github.com/EDCD/EDMarketConnector/projects/10 because we can't go just blindly adding a desktop shortcut, there **will** be users upset at us messing up their nice clean desktop.

So, this is a no-go for forcing on users and dependent on redoing the installer to actually offer options like "where to install to", and whether it creates desktop etc shortcuts.

**Comment by Rixxan** [comment]
Installer now includes option to place shortcut on desktop by default. Closing as fixed :)
