### ISSUE TITLE
23000 second cooldown

### ISSUE THREAD

**Issue by jnorthrup** [EDCD/EDMarketConnector#1543]
i really don't know what prompted this but when it started around ~23000 i nuked (rm -fr *; git reset --hard)  all the EDMC and wiped the journals (mv) but not plugins.

this is the results.  

does an over-burdoned IP address (like one IP per a geographic region) potentially trigger abuse timers ?  

![image](https://user-images.githubusercontent.com/73514/167086259-c02c288f-0988-4249-b032-a72ad309caff.png)

**Comment by Athanasius** [comment]
No, that is based on the difference between when the program recorded it last made a CAPI query and 'now'.

It suggests your computer's clock had either been set in the future by around 6 hours, and then corrected, *or* had been correct and then was set 6 hours into the past.

On Windows the stored "last CAPI query time" is in the Registry: `Computer\HKEY_CURRENT_USER\SOFTWARE\Marginal\EDMarketConnector\querytime`.   You'll need to exit out of EDMarketConnector.exe, remove that key (or set its value to `0`) and then re-run.

**Comment by jnorthrup** [comment]
presumably something will look like persistence  among these files..
![image](https://user-images.githubusercontent.com/73514/167105305-c9119d18-2a9b-453a-a143-4ea56d256ad9.png)

**Comment by jnorthrup** [comment]
solved by `vi ~/.config/EDMarketConnector/EDMarketConnector.ini `

**Comment by jnorthrup** [comment]
a recurring feature 
![image](https://user-images.githubusercontent.com/73514/167105873-d8324b8f-41e5-46c8-b845-268d2b21c440.png)

**Comment by Athanasius** [comment]
It's something with your clock.

We're using python's [time.time()](https://docs.python.org/3/library/time.html#time.time) for this.  That's the number of seconds since 1970-01-01 00:00:00.0, and is independent of local timezone settings.  So it's not going to jump around due to timezone changes and the like, it has to be your actual local computer clock time changing.

On Linux run something like this in a shell:

```bash
while :; do date +%s ; sleep 1 ; done
```

and see if the value does anything but increase by one second at a time (might sometimes not increase, or increase by two, because that `sleep 1` isn't guaranteed to be exactly 1.000 seconds, and then it has to loop around and fork/exec the `date` command).

You could also:

```bash
while :; do grep querytime ~/.config/EDMarketConnector/EDMarketConnector.ini ; sleep 1 ; done
```

To see if that specifically is jumping around.

**Comment by jnorthrup** [comment]
I do, linux and windows disagree on the offset.  i had no net-time daemon running at boot nor setting systime, it was just me adding timezone to the relatively fresh system.

**Comment by jnorthrup** [comment]
nice while : btw.
