### ISSUE TITLE
Suggestion: Calculate Balance - Insurance

### ISSUE THREAD

**Issue by CRCError1970** [EDCD/EDMarketConnector#168]
If it's at all possible, could you add a function that calculates the maximum amount of money you can spend without dropping below insurance buyback threshold for the current ship?

Also, I appreciate the minimal nature of the interface, but could you make it an option to move the tabs from the Status menu to the main window?

**Comment by Marginal** [comment]
> could you add a function that calculates the maximum amount of money you can spend without dropping below insurance buyback threshold for the current ship?

That information isn't available from the data; the total cost of your current ship *is* available (and might be slightly different from that shown in E:D Shipyard or Coriolis due to various discounts when you purchased the ship and/or modules) but the the rebuy cost (as shown in the right-hand panel) and the applicable rebuy rate (i.e. 5%, 3.75% or 2.5% for Normal, Beta or Alpha backers) aren't available. Plus, if you're intending to spend money on upgrading your ship then this would increase your rebuy cost so the calculation wouldn't be accurate anyway.

> could you make it an option to move the tabs from the Status menu to the main window

I'm not keen to do anything that would increase the size of the main window or the number of options for all users.

**Comment by inorton** [comment]
You  could do this as a plugin without too much fuss I think

**Comment by NoFoolLikeOne** [comment]
A very simple plugin could allow you to manually input your rebuy in the settings tab and then subtract it from your current balance.

Maybe you need a plugin Tag on here to tag this sort of enhancemenmt as a plugin. Then plugin devs can find them and implement if they are inclined.

**Comment by Athanasius** [comment]
It's been over 5 years.  If anyone was truly interested in this they'd have written/commissioned a plugin by now.
