### ISSUE TITLE
Can't authorise 

### ISSUE THREAD

**Issue by DM-666** [EDCD/EDMarketConnector#1843]
**Please complete the following information:**
 - Version: v5.8.1+d81c93c
 - Game Version: Horizons Live
 - OS: Windows 10
 - OS Locale: English
 - Browser: Chrome Version 108.0.5359.125 (Official Build) (64-bit)
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/10610901/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/10610902/EDMarketConnector-debug.log)

**Describe the bug**
After launch 2 tabs are opened in chrome:
1. _The server returned a "500 Internal Server Error"_. URL: https://auth.frontierstore.net/auth?response_type=code&audience=frontier,steam,epic&scope=auth
2. _This site can’t be reached_. URL: capi%26client_id%3Dfb88d428-9110-475f-a3d2-dc151c2b9c7a%26code_challenge%3Dasdffv28wbpn-pz1q9w699q-o5uhh44lfemgzuxlwvq%26code_challenge_method%3Ds256%26state%3Dhiyttmozsgn6hffghjpwvkilynsjt6q1v9gbu3fqq2o%26redirect_uri%3Dedmc.
App is stuck on 'Logging in...' 

**To Reproduce**
Start EDMC

**Expected behavior**
One of the tabs should be a Frontier authorization page? As far as I can remember I never saw that page.

**Screenshots**
![image](https://user-images.githubusercontent.com/22614952/216818143-e2820745-3f94-4f9b-a18d-6b2342b6218e.png)

**Additional context**
Launching with EDMarketConnector - localserver-auth.bat does the same thing.
Reinstall doesn't help either

**Comment by norohind** [comment]
Assuming you a bit messed up with formatting the issue message and both items under
*Describe the bug* means something like *The server returned a "500 Internal Server Error". URL: https://auth.frontierstore.net/auth?response_type=code&audience=frontier,steam,epic&scope=auth%20capi&client_id=fb88d428-9110-475f-a3d2-dc151c2b9c7a&code_challenge=<code_challenge_here>&code_challenge_method=S256&state=<state_here>&redirect_uri=edmc://auth*, it means there is a problem on FDEV side. Try to auth later, try if it's works on other tools which requires FDEV oAuth2.0 authentication and if problem persists, contact FDEV customer support. Also if you have the game in EGS (Epic Game Store) there might be problem on FDEV side which should be solved once you enter the game (though this case usually looks not like that).

**Comment by DM-666** [comment]
Excuse me for the late response, I wasn't able to check my mail.
The issue is that when I start EDMC - 2 tabs open in Chrome, both lead to nothing. The first URL looks like Frontier authorization link, but stuck at "500 Internal Server Error". The second URL looks like crap and ends up with "site can't be reached". The question is: is this an intended behavior? Should EDMC visit 2 links on startup? My guess is that it should be one link but it gets splitted in two somehow, causing a login error. How the login link should look like?
The problem exists a few weeks from the day that I installed EDMC. I used EDMC in the past without any issues, but it was like a year ago when a has Windows 7 on my PC.
I have ED on Steam. And what are the other tools requiring FDEV oAuth2.0 authentication? I would like to test them too

**Comment by norohind** [comment]
It's definitely not intended behavior. EDMarketConnector should open only one tab in order to auth, and it's URL should be as in the template I've specified.  

There are actually space between two parts of URL you're facing as opening as two tabs. It seems something between EDMarketConnector's call to *webbrowser.open()* and actually opening browser window treats space as separator between two URLs. This space is intended to encode to `%20`, I don't know which software must encode it, though it always just worked. (And at first glance I haven't found anything related to url encoding in docs to webbrowser module or in it sources) ([Current implementation in EDMarketConnector 5.8.1](https://github.com/EDCD/EDMarketConnector/blob/release-5.8.1/companion.py#L395)).
I've tested it with chrome 109.0.5414.120 64-bit official build and Firefox 109.0.1 64 bit (both windows) and it worked perfectly fine. In browser's address bar I saw url with encoded special symbols, including space encoded to `%20`.
Try to check it with another browser (you probably will need to set another browser as default). I've also noted your Chrome version isn't latest, may be upgrading to latest will solve the problem.

Other tools can be https://inara.cz and https://journal-limpet.com

**Comment by norohind** [comment]
I would leave this issue as opened if next maintainer will want to look into actually encoding URL on EDMarketConnector side to prevent cases like this. Note that it mostly won't be addressed anytime soon as there is no active maintainer for now.

**Comment by DM-666** [comment]
Good idea!

**Comment by Rixxan** [comment]
Looking through this, I'm as of yet unable to replicate this issue. however, when looking at the URL parameters I do see where it's created as:

https://github.com/EDCD/EDMarketConnector/blob/f30fb56f6e1767d05d235f6e1077dd91eddce5e0/companion.py#L395C1-L404C10

It's this `f'&scope=auth capi'` that I think might be causing the issue. (Perhaps, replace with a %20?)

Hesitant to make code changes without confirming this is the source.

**Comment by DM-666** [comment]
Stepped away from Chrome and reinstalled Windows in the meantime. It works fine atm, thank you, guys, for fixing stuff and keep it alive!
