### ISSUE TITLE
Update Build Process

### ISSUE THREAD

**Issue by Rixxan** [EDCD/EDMarketConnector#2040]
**Describe the enhancement**

The current build process is functional, but is in need of some TLC. The build file should be updated to be more in line with current pythonic standards, as well as to see if any enhancements in speed, reliability, or performance can be made. In addition, further research should be done on if py2exe is still the best option for building the project. Finally, Wix should be investigated to see if it is still the most optimal for our needs.

- [x] Current Build System Triaged
- [x] Py2Exe Fate Determined
- [x] Installer Logic Updated
- [x] Wix Fate Determined

**Comment by Rixxan** [comment]
At least with where I'm looking right now, the py2exe system is working and the wix system is working. Initial attempts to change this evening showed it would be a giant pain to replace the whole system, vs just putting it in a more maintainable state. 

Looked at PyInstaller but couldn't get a working build. Wix is annoying me and might be worth extra effort to try and knock back.

**Comment by Athanasius** [comment]
With respect to the installer/WiX.... yes, it really needs redoing.

Marginal's philosophy seemed to be to make the installer as minimal as possible, I think principally in order to have the auto-update process be as streamlined as possible.

This means there's:

1. No facility for specifying an alternate install location (without resorting to manually running msiexec on the .msi file and supplying commandline parameters).
2. No facility for pre-selecting a translation language.  In theory an installer should be able to offer selection of this and tweak the necessary EDMC config (this is all Windows, so just a registry value).
3. Provide pointers to things like the new user guide on the wiki.
4. Display any pertinent licensing (given we depend on a bunch of python modules with their own licenses).

It *should* be possible to "pretty up" the first-time installation process whilst still utilising command-line arguments to make the update process streamlined.
