### ISSUE TITLE
Give us a way to change the install path

### ISSUE THREAD

**Issue by DawnTreader** [EDCD/EDMarketConnector#2053]
**Describe the enhancement**

The installer should be given a way to change the location that the program is installed to. 
**Expected behavior**

I used to be able to do this.

**Considered workarounds**

Copy the files from the location that it installs to and put them in the location I want them.

**Additional context**

I have a drive where I keep everything for elite.

**Comment by Rixxan** [comment]
Good idea, I'll try to get this included in the next update.

**Comment by DawnTreader** [comment]
This one still counts 😄 Thanks!

**Comment by Rixxan** [comment]
In the meantime, I believe you should be able to trigger the installer to choose a new directory by uninstalling EDMC and doing a fresh install of 5.9.3. I will still investigate the ability to change the directory after the fact :)

**Comment by Rixxan** [comment]
We can't really think of a safe way to do this during an upgrade, however, the ability to choose a custom install path is available during a first-time installation. 

Because of this, we recommend saving your plugins, uninstalling EDMC, and performing a fresh install with 5.9.5. You should be able to choose a new install path during this installation.

**Comment by DawnTreader** [comment]
That's what I expected. I was installing again for the first time. There was no option to direct the install path. If you fixed that great. Thanks for your attention to this.

**Comment by Rixxan** [comment]
![image](https://github.com/EDCD/EDMarketConnector/assets/26337384/2b329186-c6e3-48df-b035-6d1858b77673)
Testing the latest version of EDMC (5.9.5), and this is indeed possible :)
