### ISSUE TITLE
EDMC authenticates, but no updates are made

### ISSUE THREAD

**Issue by rask** [EDCD/EDMarketConnector#2236]
**Please complete the following information:**
 - Version: 5.10.6+8b7923e
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/15370312/EDMarketConnector.log)
     1. [EDMarketConnector-debug-snipped.log](https://github.com/EDCD/EDMarketConnector/files/15370401/EDMarketConnector-debug-snipped.log)

**Describe the bug**
EDMC starts up fine, authenticates, but then the "Update" button does nothing, and during gameplay no live updates are sent to Inara or EDSM. When I press update a cooldown is initiated, but no data appears into the UI.

**Expected behavior**
The Update button should let me fetch my system and station, instead of it being left blank. Depending on settings my actions should be streamed to Inara etc. live.

**Additional context**
This problem started without any update or comparable triggering it from what I gather.

**Comment by Rixxan** [comment]
Hey there Rask!

Thanks for reporting. This doesn't appear to be an error with EDMC - the "Update" button isn't designed to push logs to the third party tools, it instead retreives data from the cAPI if the data is missing. This functionality is similar to what happens when you dock at a station. 

I would recommend checking your settings menu to see if you have your Inara information configured, ensuring that things are configured properly. 

![image](https://github.com/EDCD/EDMarketConnector/assets/26337384/14a9b83d-4e5b-4c25-ba15-830ba55bd586)

The logs seem to indicate you are authenticating with a valid CMDR key from the cAPI, but I don't know on first glance about the Inara sends etc. 

If these are properly configured, please let me know and we'll keep looking at it.

**Comment by rask** [comment]
The credentials are OK, and they have worked previously just fine.

**Comment by rask** [comment]
Weird, the issue seems to have resolved itself. I guess some service that EDMC contacts was just flaky for a few days.

I'll get back to this in case it happens again. I wonder if there are ways to do health checks on those services that might crap out on you.

Thanks for the help!

**Comment by Rixxan** [comment]
Glad it seems to be working again. Closing ticket, but if it comes back feel free to reopen.
