### ISSUE TITLE
Suggestion: plugin for elitegalaxyonline.com

### ISSUE THREAD

**Issue by b166er** [EDCD/EDMarketConnector#305]
it would be nice to have all-in-one application with EDMarketConnector, i send data with EDMC-app to my inara account, edsm account and eddn network, but for elitegalaxyonline.com i need to use extra app. is there a way to add this site as plugin? i think the site has a API for submitting data to their database: http://www.elitegalaxyonline.com/wp-content/uploads/2017/05/Elite-Galaxy-Online-API-Documentation-v2.1.pdf

thanks!

**Comment by KingRider** [comment]
Please plugin! +1

**Comment by GALDART** [comment]
really this plugin would be very useful, would like to use e.g.o in the E.D.M.C

**Comment by CMDR-Cometborne** [comment]
Elite Galaxy Online no longer exists, it collapsed due to the amount of data pouring in after somebody wrote a plugin for ED Discovery that transmitted the scan data automatically.  If you visit the site now, all you get is an HTTP 404 error for the start page.
Long story short: I think this issue can be closed as no longer required.

**Comment by Athanasius** [comment]
Yup, http://www.elitegalaxyonline.com/ is a 404, closing.
