### ISSUE TITLE
Prevent update window from stealing focus in the middle of a game

### ISSUE THREAD

**Issue by Marginal** [EDCD/EDMarketConnector#317]
Either:
- Only check for updates at app start; or
- Prevent update window from stealing focus

Also, update window should sit on top of app window even when app is "always on top".

**Comment by Athanasius** [comment]
The way the update checking is implemented is with a third-part library, WinSparkle.  The popup is from that external DLL code.  So unless there are some WinSparkle options we can set this behaviour can't be changed.

I do note, however, that EDMC will only check for an update every 47 hours currently, although I'm reducing that interval to 8 hours in the next (final python 2.7) release in order to better ensure users are using the latest version.

**Comment by Athanasius** [comment]
I definitely can't do anything about the update window appearing under the app window if the latter is set to 'always on top'.  Like I said, the popup is from WinSparkle's code over which I only have the control afforded by the settings and API.  We can't manipulate the window directly.

With not being able to change WinSparkle's popup behaviour what I've done instead is implement an option ('Settings ' > 'Configuration' > 'Disable Automatic Updates Check when in-game') that toggles WinSparkle's automatic checking if EDMC has detected you're fully in-game (not just at the main menu).  It will then toggle it back on if it detects you exited to the Main Menu or fully to desktop.

If you run EDMC, toggle the 'Disable' on, run the game, then toggle the 'Disable' off, you still won't get automatic update checks until after you exit to Main Menu or Desktop.

This will be a part of the next release (should be 3.46).

Commit 4d5fa590af9d3a77eac6b97de597de9dd18584b9
