### ISSUE TITLE
Update broke my shortcut

### ISSUE THREAD

**Issue by BeGlorious** [EDCD/EDMarketConnector#387]
This might not even be worth complaining about, but I'm bored, and it is technically a bug, so maybe you'll want to work on it when you get bored too.

The latest update broke my desktop shortcut to EDMC. I had to make a new shortcut. It was an easy work around.

**Comment by Marginal** [comment]
Yes, I'm afraid that every update will likely break your shortcut.

**Comment by incryptx** [comment]
I fix this by using the new shortcut created and copying & pasting it, or cutting and copying it over the broken shortcut in the start menu, or where ever your shortcut happens to be. Another workaround is to edit the "properties" of the shortcut and re-insert the correct path.

Granted an update will break it each time you update, but it is easily fixed.

**Comment by bWildcard** [comment]
my shortcut to EDMC never gets broken, How are you making a shortcut?

Goto install directory, right click on EDMC, click make shortcut, copy short cut then paste it to where ever

**Comment by Athanasius** [comment]
I've never had my own desktop shortcut for EDMC break, but I think that's because I make one manually to point at the installed .exe, rather than making a copy of the Windows Start menu shortcut.

1. Navigate to where EDMC is installed: `C:\Program Files (x86)\EDMarketConnector`
1. Right-Click on `EDMarketConnector.exe`
1. Select `Send to` and then `Desktop (create shortcut)`
1. If you prefer, now edit the name of the new shortcut.

**Comment by Artoria2e5** [comment]
With 5.9.1 replacing the msi application shortcut system with a plain exe shortcut, this issue should not happen again.

**Comment by Rixxan** [comment]
Whohoo! Closing as fixed.
