### ISSUE TITLE
Error: Frontier server is lagging

### ISSUE THREAD

**Issue by dtdionne** [EDCD/EDMarketConnector#428]
Greetings,

Great app, love it and thanks so much for the hard work.

Ive been getting this error consistently while in the SRV.  However once back in my ship, it then correctly identified my ship and replace the error with the "You're not docked..." message.  I think it may be a corner case, but just thought i'd mention it.

MUCH LOVE AND RESPECT!

David

**Comment by Athanasius** [comment]
Is this still happening with release 3.44 or later ?

**Comment by yosemitehiker** [comment]
ED Market Connector started showing this message to me about a week ago.  It always shows my location at Shinrarta Dezhra, even when I'm not there.  This is persistent, even when in my ship or SRV (no difference).  I've disabled my Plugins and EDMC still does not work for me.  Any suggestions?

**Comment by Athanasius** [comment]
"Error: Frontier server is lagging" is caused by the data returned by the Frontier CAPI service not matching the location (system and station) that was last seen in your journals.

I assume by 'always shows my location' you mean when you use the 'Update' button in EDMC ?  If it's *also* doing that when you jump between systems then you would appear to have a bad Journal Folder set.
