### ISSUE TITLE
Random crashes since update to latest version (3.4.3)

### ISSUE THREAD

**Issue by Coruin** [EDCD/EDMarketConnector#467]
Since updating to the latest version, EDMC randomly crashes with no error message. It just shuts down without any notice.

I had a look at the windows event monitor and it states that the file tcl85.dll (version 8.5.2.15) caused the issue. Exceptioncode: 0xc0000005

**Comment by Luckfish3** [comment]
I too have this issue.

**Comment by NoFoolLikeOne** [comment]
Folks could you let us know if you are using any plugins. 

There is a known issue with EDMC-Canonn which hopefully is now fixed with the latest version of the plugin

**Comment by Luckfish3** [comment]
EDMC - Alien Tour
EDMC - Canonn 5.1.1
CGTHresholds
DistanceCalc
EDMC - Autopath
EDR v.1.0.5
EDSM-RSE for EDMC
HabZone
EDMC Inara
EDMC L3-37
EDMC chatviewer

**Comment by NoFoolLikeOne** [comment]
Alien Tour? I didn't know anyone was using that! Alien Tour is a very old plugin and I won't be at all surprised if that is unstable. I may include the functionality in the next release of EDMC-Canonn as an optional patrol. and that will save you some screen space. I'd recommend you remove that one and see if it helps. 

Have you had any crashes since installing Canonn 5.1.1? That one ought to be stable. 

I think this is unlikely to be EDMC itself but probably one of the plugins.

**Comment by Luckfish3** [comment]
Just uninstalled Alien Tour on your recommendation, but won't get to try it out for several days at least...I'll let you know the results.

I'm not sure about crashes since installing Canonn 5.1.1, I generally look for plugin updates every so often. I've been running whatever the latest version of the Canonn plugin for some time now.

**Comment by NoFoolLikeOne** [comment]
The Alien tour is integrated into EDMC-Canonn and will be made available next week.

Could I have your cmdrname so I can check when you upgraded?

**Comment by Luckfish3** [comment]
Cmdr Jack Shaftoe. Looking forward to the update, and thanks for all the
work you do for it!

**Comment by NoFoolLikeOne** [comment]
Cool thanks. I can see it updated on the 8th so you should be ok.

**Comment by Athanasius** [comment]
Closing on the assumption that it was a plugin issue and hasn't recurred.
