### ISSUE TITLE
"Server is lagging" error despite correct journal directory

### ISSUE THREAD

**Issue by dbackstr** [EDCD/EDMarketConnector#473]
Hello,

Today (immediately after January update) EDMC stopped auto-updating, and began throwing the "server is lagging" error if I tried to manually update. After checking the troubleshooting guide, I checked to see if the folder had the journal.log files, and found that the app was pointing at the correct folder. I also checked the files in my text editor, and found that the journal files did indeed include details from my current play session. However, the application did not seem to be able to read the data in the latest journal file, having stopped updating at the end of the previous one.

Since I couldn't troubleshoot any further on my own, I decided to create an issue here. I couldn't find an error log file in the c:\Tmp\ folder on my disk, so I haven't attached one.

Thanks for all your work!

**Comment by Athanasius** [comment]
The log file is placed at `%TEMP%\EDMarketConnector.log` - use exactly that text (or just `%TEMP%` in a Windows (file) Explorer window) to find it.

The 'Server is lagging' message is shown when the latest known system/station position from the Journal files does not match what is received from the Frontier CAPI server (the service that EDMC requires you to auth with Frontier in order to use).  EDMC tries to use the CAPI station data for Commodities, but needs to ensure it's for the correct location, if not, it complains.

As this report was from January, and possibly due to Frontier issues, I'll close this issue.  Open a new one after testing with 3.44 if it's still happening.
