### ISSUE TITLE
Coriolis link

### ISSUE THREAD

**Issue by Vlodec** [EDCD/EDMarketConnector#495]
Using the "Ship" button to send ship configuration to Coriolis tries to send to "beta.coriolis.io", which no longer exists. I can't find where to change it. Do I have to re-install? I'm using the latest version of EDMC.

**Comment by Athanasius** [comment]
Firstly don't just state "the latest version", as either you or someone responding could be mistaken about what that means.  For EDMC use the Help menu and then "Check for updates".  It will do what it says on the tin and then either offer to update if you're not on the latest release *or* tell you the version you're running.  Currently the latest actual released version is 3.4.3.0 (although there's a 'release candidate' 3.5.0.0 based on Python 3 instead of Python 2 as well).

Now, on to the actual problem.  I've checked with both the 3.5.0.0 I originally had installed, and also then 3.4.3.0 and in both cases if I have 'Coriolis' selected in File > Settings > Configuration tab > Preferred websites > Shipyard, it goes to a plain coriolis.io URL, not a beta.coriolis.io one.

However, if you're running the beta version *of the game* it will attempt to use beta.coriolis.io, on the premise that coriolis might be updating for the upcoming patch without affecting its main site.

**Comment by Athanasius** [comment]
NB: I've brought this up with the person that currently runs Coriolis, but he's on Australian time so it could be another 8-12 hours before he even sees the message.

**Comment by Athanasius** [comment]
For now you can just edit the URL in your URL bar to take the 'beta.' out of the URL and it will use the main site anyway when you're running the beta version of the game.
