### ISSUE TITLE
Ship is not displaying but IS hotlinked

### ISSUE THREAD

**Issue by msteele999** [EDCD/EDMarketConnector#614]
**Describe the bug**
Version: 4.0.2.0
Windows 7 Pro Home

Regardless of display mode, the Ship name is not displayed but it IS linked and will open shipyard web interface. 

**Expected behavior**
Ship name (i.e. DiamondBack Explorer) should be displayed.

**Screenshots**
![Screenshot_071920_015759_PM](https://user-images.githubusercontent.com/6474337/87881587-48307980-c9c8-11ea-8e14-2db22eb221f8.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home Pro
 - If applicable: Browser [e.g. chrome, safari]
 - Version 4.0.2.0

**Comment by Athanasius** [comment]
If this occurs without the game running, but then hitting 'Update' to get the UI to populate then it might be related to the name symbol for 'DiamondBack Explorer' in Frontier CAPI data not being properly mapped to a 'human' name.  In this case we would need you to use 'File' > 'Save Raw Data' and attach the resulting file to this bug report.

Otherwise we would need you to attach the most recent Journal file from when this happens to this bug report.  `shell:SavedGames\Frontier Developments\Elite Dangerous`.

Does this happen if:
 1. Your last game session included actually logging fully into the game, not just into the Main Menu.
 1. You exit the game
 1. You re-run EDMarketConnector.

In this state the application would be picking up your most recently used ship from the Journal file and the bug is something to do with the parsing of that file and/or subsequent processing.  In this case

**Comment by Athanasius** [comment]
Wait, what *is* your ship name?  Not the *model*, the *name* you can assign to it in livery ?

**Comment by msteele999** [comment]
I don't think I named this one. I will check shortly

**Comment by Athanasius** [comment]
If you didn't then it's possible the CAPI might be putting that '_' in for some reason.  We'll need the 'Save Raw Data' output to be sure.

**Comment by msteele999** [comment]
Raw Data Save attached.

**Comment by Athanasius** [comment]
> Raw Data Save attached.
> […](#)
It doesn't look like those come through via email.  Please come to GitHub (URL is in the email) and attach it in a comment.

**Comment by msteele999** [comment]
Attached via github interface


[Pro Eurl VG-K c22-12.2020-07-20T14.24.04.zip](https://github.com/EDCD/EDMarketConnector/files/4949403/Pro.Eurl.VG-K.c22-12.2020-07-20T14.24.04.zip)

**Comment by Athanasius** [comment]
Hmmm, that does indeed have ship->name as `DiamondBackXL`.  I'll do some testing with this tomorrow.  Thanks.

**Comment by msteele999** [comment]
My pleasure - the tool is awesome - I have been using it for a long time. I
was the one who originally requested a 'dark mode' so I'm thrilled to see
it still being actively developed.

Mark

**Comment by Athanasius** [comment]
I can get a **blank** ship name to show up.  Just purchase any ship, then log out and back in.  There's blank `ShipName` in the `LoadOut` journal event and EDMC uses that.  But that doesn't explain the reporter seeing `_` as the name!

**Comment by Athanasius** [comment]
aha!  That `_` is because you get a space character there, or otherwise minimum URL text and it shows on mouse over in the default EDMC skin.  OK, this just needs some code to check for ShipName = `''`.

**Comment by Athanasius** [comment]
No, it's actually because you get:

     "event":"Loadout", "Ship":"diamondbackxl", "ShipID":31, "ShipName":" ",

in the journal after a relog!  So, here's hoping no-one *WANTS* to call their ship `<literal space character>`.

**Comment by Athanasius** [comment]
Yup, easy fix.  This will be in whatever is the next full release after 4.0.2.0.  Probably a 4.0.3 once we nail down the fix for #616

**Comment by msteele999** [comment]
Outstanding - thank you!

**Comment by Athanasius** [comment]
Please try out [4.0.3-rc3](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.0.3-rc3) .

NB: If you happened to try any of the earlier 4.0.3-rcX series please **uninstall** EDMC first, then install -rc3.  All your configuration and third-party plugins will be unaffected (assuming you put third-party plugins in the correct place, not the install folder!).

**Comment by Athanasius** [comment]
Closed as [4.0.3](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.0.3) is now out.
