### ISSUE TITLE
Multiple Authorizations

### ISSUE THREAD

**Issue by StreamTalker** [EDCD/EDMarketConnector#679]
Man I love your work BUT for several updates in recent months, every time I dock I get the Frontier Authorization browser.
I have seen your comment about use the 2nd one but this is a fallacy, it still does it every time I dock.
I find that from being one of your strongest supporters and promoters of EDMC, I have now turned into one of those that says it is so unreliable that folks should no longer use it.

Hope you can remedy this fatal flaw soon Sir

**Comment by Athanasius** [comment]
Each time you dock is when EDMC fires off a CAPI request.  For this to cause EDMC to open a Frontier Authorization tab/window it must have had both its current Access Token *and* its current Refresh Token rejected by Frontier, so that it needs to ask you to authorize it to get a new one.

With this being literally each time you dock this can't only be an issue with EDMC failing to store the Refresh Token in the Windows Registry because it would be storing it internally during the same EDMC session (i.e. I'm assuming you're not closing and re-opening EDMC).  This would point towards the Frontier end of things being the problem.

Do you use any other program that utilises the Frontier Authorization, and if so do you encounter similar issues with it ?

I would ask you to check on https://user.frontierstore.net for what's listed on "Authorized Applications" but this is currently giving me an error.

Do you use only the one Elite Dangerous/Frontier account, or do you have multiple?  Have you undergone a Commander rename?

Use the Windows Registry Editor (regedit.exe) to check what you have at the path `Computer\HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector`.  For the Frontier Authorization it's the `fdev_apikeys` key.  **DO NOT PASTE THE CONTENTS OF ANY OF THE 'keys' VALUES HERE**, as that would be giving anyone reading access to your account.  The `fdev_apikeys` should have a string in it of the general form `3e79a43f-ae84-7eaf-3ad3-a7ea1f1b6b1b`, is that present ?

If that is present, and even correct, then perhaps an alternative error is that for some reason Frontier's CAPI server is rejecting any and all requests for your account.  Again, does this work with any other programs or facilities ?  NB: I believe neither EDDI nor EDDiscovery make use of the CAPI.  EliteLogAgent might.

**Comment by alterNERDtive** [comment]
[Inara](https://inara.cz) and [FCMS](https://fleetcarrier.space) also query the API, if you are using these. Inara should display an error in the settings if it has problems with it.

**Comment by Athanasius** [comment]
Also, could you please start EDMC up, login to the game, and have this issue trigger at least once and then attach the resulting `%TEMP%\EDMarketConnector.log` file to this bug report.  There might be clues in there.  Be sure you attach the file *as soon as* the issue occurs, particularly *not* after closing EDMC and starting it again as that will overwrite the file.

**Comment by StreamTalker** [comment]
It appears that the issue was on Frontier's end and not the fault of EDMC.
I truly appreciate your prompt, detailed response and look forward to remaining an avid fan of EDMC.
Thank you for your time and apologies for wasting your time <Ö
