### ISSUE TITLE
not logging in

### ISSUE THREAD

**Issue by Eradicator070** [EDCD/EDMarketConnector#681]
Hi  

I had to  reinstall  some software  & When i reinstalled  E D Market Connector  it will not connect 
the EDSM  Credential  is Blank * I cant  access this it's just greyed out  the same with Inara 
Can some one help  thanks 

Eradicator 070

**Comment by Athanasius** [comment]
The most recent journal file needs to have had you logged all the way into the game so that EDMC knows the Commander to associate credentials with.  The easiest thing is just to login to the game, then the EDMC UI/preferences bits should be unlocked.

**Comment by Eradicator070** [comment]
Hi

No that does not work, all the rest is ok but the parts you can see in the screen dump .

yes, I did log into the game it still did not work . Hope you can Help

Kind regards

Eradicator070


________________________________

**Comment by Eradicator070** [comment]
Hi

No that does not work, all the rest is ok but the parts you can see in the screen dump .

yes, I did log into the game it still did not work . Hope you can Help

Kind regards

Eradicator070



________________________________

**Comment by Athanasius** [comment]
> Hi No that does not work, all the rest is ok but the parts you can see in the screen dump . yes, I did log into the game it still did not work.

I'm not seeing any 'screen dump' this end.

Let's back up.

You didn't even state what version of EDMC you're using (am I going to have to remove the ability to NOT use one of the templates, given this is obviously a bug report?).

Ideally you'd supply a screenshot of the EDMC Settings dialogue with the EDSM tab selected, along with the `%TEMP%\EDMarketConnector.log` file from when you do that.

If `Cmdr` isn't filled in on that tab then your EDMC doesn't think it yet knows your logged in commander name.  This might point towards you having changed the `E:D journal file location` from the default to an incorrect location.  That's on the 'Configuration' tab of Settings.

**Comment by Eradicator070** [comment]
Hi

sorry for the bother i forgot to clik on the screen dumps so i sen a second one Ill also place in this one I may have set it up wrong when installing again . can you tell mw where it all should go thanks
I am using the latest update 4.0.6

kind regards

Eradicator070

________________________________

**Comment by Athanasius** [comment]
I left this overnight as you've still not provided any screen dumps.  Perhaps try replying here on github rather than in email.

I'm attaching four screenshots to this reply:

1. How the main UI looks because I started the game but am sat at the main menu, thus EDMC doesn't yet know my Commander Name.
1. How the Settings > EDSM tab looks in that state.
1. How the Settings > Inara tab looks in that state.
1. The Configuration tab where you set the Journal File location.

![01-Main-UI](https://user-images.githubusercontent.com/118007/92303510-7d3f5e00-ef6d-11ea-99c8-240aed8b949f.png)
![02-Settings-EDSM](https://user-images.githubusercontent.com/118007/92303511-7dd7f480-ef6d-11ea-9c07-ec0448dc6fcd.png)
![03-Settings-Inara](https://user-images.githubusercontent.com/118007/92303513-7dd7f480-ef6d-11ea-9ff3-940ac49a5805.png)
![Settings-Configuration](https://user-images.githubusercontent.com/118007/92303520-84666c00-ef6d-11ea-8ad4-e47f325b00c0.png)

Please check how you have the latter configuration set.  If EDMC can't find your Journal Files at all then it can't know your Commander Name and won't operate at all.

**Comment by Eradicator070** [comment]
Hi

I tried it today the way you Sade thanks, it worked happy days Cheers a lot


kind regards

Eradicator070
________________________________
