### ISSUE TITLE
Application does not handle links properly

### ISSUE THREAD

**Issue by Mr6647** [EDCD/EDMarketConnector#682]
Attempting to log in via the EDMC created Firefox or Edge window results in an EDMC application link being opened but not processed by EDMC. The app therefore never logs in and constantly displays "Logging in..." Clicking the update button opens another authentication window where the process repeats.

**Comment by Athanasius** [comment]
You are reporting a bug, please use the Bug Reporting template so that you actually supply all of the information that we need:

https://github.com/EDCD/EDMarketConnector/issues/new?assignees=&labels=bug%2C+unconfirmed&template=bug_report.md&title=

**Comment by Athanasius** [comment]
My apologies, I've since realised that some of our documentation was pointing directly to the 'raw' issue submission form.

Still, we need the extra information prompted for in that Bug Report template, so please open a new issue with it all filled out.

My first guess as to the cause of the issue you've seen is an Anti-Virus or Software Firewall preventing either the setup of the `edmc://` listener, or the communication between it and the main EDMC thread.  The EDMarketConnector.log might contain information to confirm this.
