### ISSUE TITLE
[Errno 13] Permission Denied

### ISSUE THREAD

**Issue by saintguardian48** [EDCD/EDMarketConnector#785]
- Version 4.1.4
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Browser Chrome
 - Please attach log files:
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5633709/EDMarketConnector-debug.log)

**Describe the bug**
I start up E:D Market Connector without any issues.  I have a cooldown time which allows me to get in-game.  I get in-game and on a station.  I press update and it gives me some sort of gathering then gives me an error code [Errno 13] Permission denied: Then lists the file name.  I searched for the file name

**To Reproduce**
1. Start E:D Market Connector
2. Start Elite Dangerous:Horizons
3. Click on continue
4. Click any option you wish
5. Wait for the game to finish loading and click Update on E:D Market Connector
6. See Error on E:D Market Connector

**Expected behavior**
Expected to have it update and not have any errors whatsoever.  Expecting a cooldown.

**Comment by Athanasius** [comment]
You have an EDMC option active to write station market data to a file.  You have the location set to (I think the default) of `C:\\Users\Tim\Documents\`, but the user you're running EDMC as apparently doesn't have write permissions there.

This suggests you've done something strange with your Documents folder and isn't itself an EDMC problem.

Please confirm you're just 'simply' running EDMarketConnector.exe, and not, for instance, running "As Administrator" or otherwise using "Run As ...".

You could also go to the EDMC Settings and untick the options on the Output tab to save market data to a file.

**Comment by saintguardian48** [comment]
I have E:D Market connector running as administrator in case it was asking for permission.

Please mark this as solved.  I move the file location to another drive and it works perfectly.  Thank you for pointing out that my documents might have changed settings without me knowing.  Thank you!
