### ISSUE TITLE
Authorize

### ISSUE THREAD

**Issue by ariel13795** [EDCD/EDMarketConnector#786]
It's normal that I need to authorize every time I dock up?I ale a little confused

**Comment by Athanasius** [comment]
Is this with an Epic Games Store copy of Elite Dangerous?  It seems there are initial issues with those accounts the the Frontier Auth/CAPI use.  It might start working later, try again tomorrow and report back.

I'll try and get around to properly setting up my EGS account to test so as to at least document any issues I can confirm.

Note also: https://github.com/EDCD/EDMarketConnector/wiki/New-user-guide#you-need-to-be-fully-logged-into-the-game-ie-opensolo-play

**Comment by ariel13795** [comment]
It's a steam game linked to Frontier

**Comment by Anticosmos** [comment]
I have the same error. It was working fine yesterday. Everytime when i press refresh asking me to login and also giving me" query failed after refresh" error.

**Comment by Athanasius** [comment]
Could you both please supply us with the log files and other information as per the bug report template (which really every bug should be using, not a blank issue): https://github.com/EDCD/EDMarketConnector/issues/new?assignees=&labels=bug%2C+unconfirmed&template=bug_report.md&title=

**Comment by Anticosmos** [comment]
Deleting temp files solve the problem.

**Comment by Athanasius** [comment]
> Deleting temp files solve the problem.

As described the problem has nothing to do with temporary files or directories.  I think you just had an intermittent problem (Frontier's end) that happened to resolve itself at the point you deleted temp files.

EDMC *does* have an issue if it can't open `%TEMP%\EDMarketConnector.log` as it starts up, but that would lead to it not running at all rather than having issues later on with Frontier CAPI access.

**Comment by MarcusSuridius** [comment]
I have this issue as well, I have tried finding the log files but can't find them anywhere.

Can someone explain what temp is on this - %TEMP%\EDMarketConnector.log

I have checked appdata folders, the x86 folder on my OS drive and can't find any logs.

**Comment by Athanasius** [comment]
> Can someone explain what temp is on this - %TEMP%\EDMarketConnector.log

Open a File Explorer (i.e. where you'd go for 'My Documents') window, and replace the current folder path and name with `%TEMP%`, then press return. That will get you to the correct place to then look for the file `EDMarketConnector.log`.

**Comment by capi** [comment]
I have the same issue: authentication (via Firefox) seems to work, but as soon as I press update, it reports `query failed after refresh`.

Logfile indicates some bad requests (400, on companion.orerve.net) and internal server error (500, on auth.frontierstore.net). Maybe it has something to do that my commander has a space in it's name?
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5721457/EDMarketConnector-debug.log)

**Comment by Athanasius** [comment]
> Maybe it has something to do that my commander has a space in it's name?

It shouldn't.  EDMC has otherwise always been fine with that (the original developer had a space in their Commander name as per the screenshots on https://github.com/EDCD/EDMarketConnector/wiki ).  We also don't pass the commander name as part of the authorisation, although we will check the returned data from a subsequent query matches on that field.

**Comment by capi** [comment]
I can tell that it is working since some time again. Maybe it was some server-side glitch in the API. I can't comment if it also works for the initial reporter, though.

**Comment by Athanasius** [comment]
@ariel13795 is this still happening for you with 4.2.3 ?
