### ISSUE TITLE
unable to get token

### ISSUE THREAD

**Issue by khasrahh** [EDCD/EDMarketConnector#800]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version 4.1.4
 - OS: Windows 10
 - OS Locale: German
 - If applicable: Firefox, Chrome, Edge

**Describe the bug**
The EDMC client fails to login to the Frontier Developments API

**To Reproduce**
1. Start EDMC client
2. Wait for the browser to show the API login page
3. login with credentials
4. EDMC client shows error "unable to get token"

**Expected behavior**
Successful login to the Frontier Developments API

**Screenshots**

**Additional context**
Removing everything from the API login URL after https://auth.frontierstore.net renders in a successful login.
Removing the EDMC client from authorized apps leads to the authorization site after successful login.

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5673880/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5673882/EDMarketConnector.log)

**Comment by Athanasius** [comment]
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='auth.frontierstore.net', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x06B5E130>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))`

You appear to have a firewall or the like denying the connection that would actually retrieve the token.

**Comment by khasrahh** [comment]
Darn, you are right. For some reason my anti-virus program found the EDMC client with a different name and thus blocked it. :(

Thanks for the quick reply.
