### ISSUE TITLE
Documented `ShutDown` event doesn't appear to be sent

### ISSUE THREAD

**Issue by sersorrel** [EDCD/EDMarketConnector#807]
PLUGINS.md suggests that you can tell when the game exits by listening for a `ShutDown` event:

https://github.com/EDCD/EDMarketConnector/blob/104963ceb115848816552d0cf5e7a59303aadc3c/PLUGINS.md#L421-L423

but the event written by the game is `Shutdown`. I've never seen a `ShutDown` event.

If it's expected that plugins should handle event names case-insensitively, perhaps that should be documented?

**Comment by Athanasius** [comment]
As written the documentation is 100% correct.

The `ShutDown` event is special, and by that the documentation means that it's generated by EDMC itself.  The scenario is where the game might have crashed, and thus not have written a `Shutdown`, then EDMC detects the new journal from a fresh run of the game, realises that it missed the `Shutdown` event, so generates a `ShutDown` event.  Remember, you might restart the game client, get a new Journal started, but then not actually go in-game.

Now, that code predates my maintaintership of the code.  I don't know whether Marginal had a brainfart when capitalising `Down`, or if this was intentional so that a plugin *if it wishes to* can determine that this isn't the actual game clena `Shutdown` event, but instead this detection after a restart.

At this stage I'm inclined to leave the code as-is, but will make this more explicit in PLUGINS.md.
