### ISSUE TITLE
Invalid Credentials - all boxes greyed out

### ISSUE THREAD

**Issue by ABCHammerstein** [EDCD/EDMarketConnector#937]
Won't log in. States "Invalid Credentials"
The API slots for all the tabs are greyed out and empty. Cannot re-input the API codes.
EDMC is the latest version.

**Comment by Athanasius** [comment]
1. You didn't use the Bug Report template.  This means you've not actually stated your version ("latest" doesn't actually give us any solid information), and you haven't supplied log files.

2. For "Invalid Credentials" have you read and checked https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#error-invalid-credentials ?

3. The API slots are greyed out because the game can't yet determine your Commander name, see https://github.com/EDCD/EDMarketConnector/wiki/New-user-guide#you-need-to-be-fully-logged-into-the-game-ie-opensolo-play

**Comment by Athanasius** [comment]
Closing this due to the lack of user feedback.  It was likely them not having an in-game latest Journal file with commander created and thus data available.
