### ISSUE TITLE
EDMC Continually detecting "A New Version"

### ISSUE THREAD

**Issue by toqueville** [EDCD/EDMarketConnector#958]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**
Checked.  Did not see.
**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.
Checked.  Did not see.

**Please complete the following information:**
 - Version 4.2.5
 - OS: Windows 10
 - OS Locale: US English
 - Please attach **BOTH** log files as follows:
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6230265/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6230266/EDMarketConnector.log)

**Describe the bug**
Upgrade notification re-notifies after updating to the latest.  Started happening with (I believe) 4.1.6 and has continued with 4.2.5. I have to 'ignore this version' to keep it from re-appearing, even though I'm running the version it is notifying me about.
**To Reproduce**
1. Update to latest.
2. Re-receive update popup.

**Expected behavior**
I expected to not receive a notification that I was out of date running the latest code. 
**Screenshots**
![image](https://user-images.githubusercontent.com/650139/113017282-4caf5380-914d-11eb-83cc-41f4cc6641ff.png)

**Comment by Athanasius** [comment]
Well, this is a puzzler.

Windows 10 build 19042, so same as me.  It works here, and your EDMC is clearly showing the correct current version, plus it's obviously downloading the correct 'appcast' file to find the update.

There shouldn't be any way to have '4.1.6' get passed to the WinSparkle library we use for the automatic update checks whilst having '4.2.5' in the About popup.  If anything I'd expect total garbage rather than '4.1.6'.

Are you sure you don't still have 4.1.6 installed and running as well as 4.2.5 ?

I can only suggest that you:

1. Quit EDMarketConnector.exe
2. Open Windows Settings (`WinKey + I`)
3. Go to 'Apps' and wait for it to load the list.
4. Type 'Market' in the search box.  Check what version that says and tell us.
5. Then Uninstall whatever version that is.
6. Double-check there's still no other listing for the program.
7. Re-install using the .msi file from https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.5

**Comment by toqueville** [comment]
Did all those.  Only had one, 2.4.5.

Poking around further, I do note that I have an errant python process running. This does run a python exec under the cover, right?  I don't run from source, so I don't know how a python.exe version of this app would have started up.  I don't know enough about the failure modes of py2exe to comment there.  I'll see if this recurs after the next update.  But this smells to me like the source of the issue.

**Comment by toqueville** [comment]
![image](https://user-images.githubusercontent.com/650139/113081333-7cd71080-91a6-11eb-9c5c-fea638c062d1.png)
?  Any ideas what this is?

**Comment by Athanasius** [comment]
An RBF file is apparently a "Roll Back File".

https://fileinfo.com/extension/rbf
https://file.org/extension/rbf
https://www.filemagic.com/en/backup-files/rbf-file-extension/rbf-files-what-it-is-and-how-to-open-it/

So, either something weird going on with installing things on your system, or you have some backup software that's responsible ?

**Comment by toqueville** [comment]
Got Acronis, but it writes to a hdd image on a weekly schedule.  It doesn't muck with uninstall/install files or creates RBF's when installing new versions.  Weird.  My gaming desktop appears to have picked up a slight flutter.

**Comment by toqueville** [comment]
Eh, I'm willing to check this up to something strange going on unrelated to the code you guys produce.
